### ISSUE TITLE
Any way I can adjust the volume of the input in the codes?

### ISSUE THREAD

**Issue by vasinl124** [closeio/mic-recorder-to-mp3#29]
I compare the audio file I got from Chrome and Safari and found out that the volume in Chrome is really low. Does anybody notice this? 

So is there any way I can adjust the volume in the code to make it louder?

Thanks

**Comment by buzinas** [comment]
Currently, there is no way to adjust the volume.

If we allow custom media constraints (as requested in [this issue](https://github.com/closeio/mic-recorder-to-mp3/issues/15)), you'd be able to use [`volume`](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/volume). That said, this is a deprecated setting though, since it's invasive to the user.
